title: India Mutual Funds API
email: mf@captnemo.in
description: Get information about Indian Mutual Funds from their ISIN numbers.
url: "https://mf.captnemo.in"
twitter_username: captn3m0
github_username:  captn3m0
theme: jekyll-theme-modernist
github:
  repository_url: https://github.com/captn3m0/mf.captnemo.in
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - _scripts
  - netlify.toml
  - vendor
  - Makefile
  - README.md
  - LICENSE
  - nav/.gitkeep
include:
  - _redirects
  - _headers
  - nav
# Not supported yet
csv_reader:
  col_sep: ';'
markdown: kramdown
kramdown:
  parse_block_html: true
