name: Update Data
on:
  schedule:
    # Run every 2 hours
    - cron: '30 */2 * * *'
jobs:
  update:
    name: Update data
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Update data
      run: make all
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update MF Data
        commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
